feat(OrderClient): new dates and status for orderclients
OPEN-ENT-NG/lystore pull request #127
Opened 2023-04-20 07:05 UTC by Rseuret

## Describe your changes
add new dates and get status with isntruction cp
## Checklist tests

## Issue ticket number and link
https://jira.support-ent.fr/browse/MLYSTOR-603
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-20 12:01 UTC, Rseuret commented on src/main/resources/public/template/customer/campaign/order/orders-by-equipment.html
> -    <div class="cell width-100-40">
refacto

2023-04-20 12:01 UTC, Rseuret commented on src/main/resources/public/template/customer/campaign/order/orders-by-project.html
> -                <div class="cell width-100-40">
refacto

2023-04-20 12:02 UTC, Rseuret commented on src/main/resources/public/ts/controllers/administration/labelOperation.ts
> +import {Label, Utils} from "../../model";
refacto label -> Label

2023-04-20 12:03 UTC, Rseuret commented on src/main/resources/public/ts/model/OrderClient.ts
> +        //à transformer en contact
commentaire fait pour futures évos

2023-04-20 12:04 UTC, Rseuret commented on src/main/resources/public/ts/model/operation.ts
> +import {Label} from "./LabelOperation";
refacto label > Label

2023-04-20 12:10 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/main.ts
> +                await orderService.sync(idCampaign,$scope.current.structure.id).then( result =>
si tu fais un then, tu peux enlever le await !

2023-04-20 12:11 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/main.ts
> +                await orderService.sync(idCampaign,$scope.current.structure.id).then( result =>
si tu fais un then, tu peux enlever le await !

2023-04-20 12:13 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/viewer/order-list.ts
> +            console.log("deleteProject")
supp le console log

2023-04-20 12:14 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/viewer/order-list.ts
> +            await orderService.sync($routeParams.idCampaign, $scope.current.structure.id).then( result =>
tu peux enlever ton await

2023-04-20 14:11 UTC, JinDouang requested changes

2023-04-20 14:11 UTC, JinDouang commented on src/main/java/fr/openent/lystore/service/impl/DefaultProjectService.java
> +                                double purse_amount = 0.d;
Si possible, faire en camelCase (https://rules.sonarsource.com/java/tag/convention/RSPEC-117)

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/directives/order-client-display-viewer/order-client-display-viewer.directive.ts
> +        replace: true,
Tu n'es pas obligé de mettre `replace: true`

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/directives/order-client-display-viewer/order-client-display-viewer.directive.ts
> +        return " : Rapport " + this.orderClient.operation.instruction.cp_number;
Possible de le gérer en i18n ?

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/directives/order-client-display-viewer/order-client-display-viewer.directive.ts
> +        return lang.translate(this.orderClient.status)
```suggestion
        return lang.translate(this.orderClient.status);
```

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/directives/order-client-display-viewer/order-client-display-viewer.directive.ts
> +            return orderClient.operation.instruction.object
```suggestion
            return orderClient.operation.instruction.object;
```

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/directives/order-client-display-viewer/order-client-display-viewer.directive.ts
> +            return lang.translate(orderClient.status) + " " + orderClient.operation.label
```suggestion
            return lang.translate(orderClient.status) + " " + orderClient.operation.label;
```

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/directives/order-client-display-viewer/order-client-display-viewer.directive.ts
> +        let totalPrice = this.calculatePriceOfOrderClient(orderClient, true, roundNumber) * orderClient.amount;
typage

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/model/OrderClient.ts
> +            this.options = orderClientResponse.options.map(options => {
typage `options ` dans ta map

tu pourrais aussi le faire en une ligne : 

```suggestion
            this.options = orderClientResponse.options.map((options: IOrderClientOptionResponse) => new OrderOptionClient().build(options));
```

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/model/OrderClient.ts
> +        this.all.forEach(order =>{
typage

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/model/OrderClient.ts
> +        })
```suggestion
        });
```

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/model/OrderClient.ts
> +            if(this.projects.filter(projectFiltered => projectFiltered.id === order.project.id).length === 0)
typage

2023-04-20 14:11 UTC, JinDouang commented on src/main/resources/public/ts/services/app/index.ts
> +export * from './viewer/index'
```suggestion
export * from './admin/index';
export * from './viewer/index';
```

2023-04-21 08:16 UTC, JinDouang requested changes

2023-04-21 08:16 UTC, JinDouang commented on src/main/java/fr/openent/lystore/service/impl/DefaultOrderService.java
> +                handler.handle(new Either.Left<>(event.left().getValue()));
log erreur (avec string.format etc...) si possible!

2023-04-21 08:25 UTC, JinDouang approved these changes

2023-04-21 08:48 UTC, merged