Feat(OperationOrder): #MLYSTOR-597 change display order operation to match order waiting
OPEN-ENT-NG/lystore pull request #134
Opened 2023-05-22 07:42 UTC by Rseuret

## Describe your changes
display order operation to match order waiting

/!\Pr urgente donc les retours non bloquants ne seront peut être pas traités
## Checklist tests
check if each column works properly

## Issue ticket number and link
https://jira.support-ent.fr/browse/MLYSTOR-597

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-05-22 07:53 UTC, Rseuret commented on src/main/java/fr/openent/lystore/service/impl/DefaultOrderService.java
> -        String query = "SELECT oce.id, oce.price, oce.tax_amount, oce.amount, oce.creation_date, oce.id_campaign, oce.id_structure, oce.name, oce.summary, oce.description," +
indentation

2023-05-22 14:37 UTC, lapeyronnie requested changes

2023-05-22 14:37 UTC, lapeyronnie commented on src/main/java/fr/openent/lystore/service/impl/DefaultOperationService.java
>                  " orders.override_region," +
est-ce normal que price_proposal, soit présent deux fois ?

2023-05-22 14:37 UTC, lapeyronnie commented on src/main/resources/public/ts/controllers/main.ts
>                  template.open('administrator-main', 'administrator/operation/operation-container');
ce n'est pas ordersClientByOperation.all ?

2023-05-22 15:36 UTC, qpic-cgi approved these changes

2023-05-22 15:36 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/display-order-list/display-order-list-table/display-order-list-table.html
> +                <td ng-if="vm.tableFields[0].display"> <div class="smallTabElem"> [[order.structure.uai]]</div></td>
tu es obligé de gérer ça avec des index ? l'idéal serait un ng-repeat

2023-05-23 06:10 UTC, Rseuret commented on src/main/resources/public/ts/directives/display-order-list/display-order-list-table/display-order-list-table.html
> +                <td ng-if="vm.tableFields[0].display"> <div class="smallTabElem"> [[order.structure.uai]]</div></td>
oui j'ai vu avec jin et je suis obligé de passé par l index

2023-05-23 06:43 UTC, Rseuret commented on src/main/resources/public/ts/controllers/main.ts
>                  template.open('administrator-main', 'administrator/operation/operation-container');
je ne comprends pas le commentaire

2023-05-23 07:36 UTC, JinDouang requested changes

2023-05-23 07:36 UTC, JinDouang commented on src/main/resources/public/ts/directives/display-order-list/display-order-list-table/display-order-list-table.html
> +                <td ng-if="vm.tableFields[0].display"> <div class="smallTabElem"> [[order.structure.uai]]</div></td>
Yes vu avec moi, c'pas gênant pour l'instant

2023-05-23 07:36 UTC, JinDouang commented on src/main/resources/public/ts/directives/display-order-list/display-order-list-table/display-order-list-table.directive.ts
> +    allOrdersSelected:boolean
;

2023-05-23 07:36 UTC, JinDouang commented on src/main/resources/public/ts/directives/display-order-list/display-order-list-table/display-order-list-table.directive.ts
> +    }
;

2023-05-23 12:09 UTC, JinDouang approved these changes

2023-05-23 14:10 UTC, merged