chore() #MLYSTORE-747 :Service factory
OPEN-ENT-NG/lystore pull request #161
Opened 2023-07-27 14:34 UTC by Rseuret

## Describe your changes
Refactoring : adding ServiceFactory

## Checklist tests
-Check Exports
-Check Operation and instructions
## Issue ticket number and link

https://jira.support-ent.fr/browse/MLYSTOR-747

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-07-27 14:35 UTC, Rseuret commented on src/main/java/fr/openent/lystore/Lystore.java
> +        addController(new ActiveStructureController(serviceFactory));
tri par ordre alphabétique en plus de l'ajout du serviceFactory

2023-07-27 14:36 UTC, Rseuret commented on src/main/java/fr/openent/lystore/export/instructions/RME/RecapEPLETab.java
> -        structureService = new DefaultStructureService(Lystore.lystoreSchema);
service non appelé donc suppression

2023-07-28 15:07 UTC, qpic-cgi requested changes

2023-07-28 15:07 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExport.java
> +    public BCExport(EventBus eb, Vertx vertx, JsonObject config, Storage storage, ServiceFactory serviceFactory) {
utilise vertx / config / storage de ton serviceFactory

2023-07-28 15:07 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportAfterValidation.java
> +    public BCExportAfterValidation(EventBus eb, Vertx vertx, JsonObject config, Storage storage, ServiceFactory serviceFactory) {
utilise eb / vertx / config / storage de ton serviceFactory

2023-07-28 15:07 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportAfterValidationStructure.java
> +        super(eb, vertx, config, storage, serviceFactory);
utilise eb / vertx / config / storage de ton serviceFactory

2023-07-28 15:07 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportBeforeValidationStructure.java
> +        super(eb, vertx, config, storage ,serviceFactory);
utilise eb / vertx / config / storage de ton serviceFactory

2023-07-28 15:07 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportDuringValidation.java
> +        super(eb, vertx, config, storage, serviceFactory);
utilise eb / vertx / config / storage de ton serviceFactory

2023-07-28 23:46 UTC, JinDouang requested changes
je partage également le retour de q3

2023-07-28 23:46 UTC, JinDouang commented on src/main/java/fr/openent/lystore/service/ServiceFactory.java
> +package fr.openent.lystore.service;
Tu peux mettre ton ServiceFactory plutôt dans un nouveau package "factory" ?

2023-08-01 14:47 UTC, qpic-cgi approved these changes

2025-08-21 09:15 UTC, closed without merging