feat(Parameter)#MLYSTOR-626: add new parameter page
OPEN-ENT-NG/lystore pull request #89
Opened 2023-01-30 10:30 UTC by Rseuret

## Describe your changes
Ajout d'une nouvelle page de paramétrage pour les ADMC. 

**ACTUELLEMENT LA PAGE NE FONCTIONNE PAS CAR LES APIS NE SONT PAS PRÉSENTES**
L'image n'est également pas fonctionnel
## Checklist tests

Cliquer sur un switch ou sur le bouton confirmer doit faire apparaitre un toast "Changements sauvegardés"
Cliquer sur "Annuler" reset le formulaire (sauf l'image)

## Issue ticket number and link
https://jira.support-ent.fr/browse/MLYSTOR-626
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-30 13:51 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/controllers/LystoreController.java
> +                                    params.put("isSuperAdmin", isAuthorized);
constant

2023-01-31 08:12 UTC, lapeyronnie approved these changes

2023-01-31 10:33 UTC, JinDouang requested changes

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/active-structure/active-structure.controller.ts
> +            toasts.warning("lystore.parameter.update.error")
manque la ; 
```suggestion
            toasts.warning("lystore.parameter.update.error");
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/active-structure/active-structure.controller.ts
> +            toasts.info("lystore.undeploy.structure.valid")
manque la ;

```suggestion
            toasts.info("lystore.undeploy.structure.valid");
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/active-structure/active-structure.controller.ts
> +            toasts.info("lystore.deploy.structure.valid")
manque la ;

```suggestion
            toasts.info("lystore.deploy.structure.valid");
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/active-structure/active-structure.controller.ts
> +        Utils.safeApply(this.$scope)
manque la ;

```suggestion
        Utils.safeApply(this.$scope);
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/active-structure/active-structure.controller.ts
> +            Utils.safeApply(this.$scope)
manque la ;


```suggestion
            Utils.safeApply(this.$scope);
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/parameter-main.controller.ts
> +    };
```suggestion
    redirectToHref = (path: string): void => {
        this.$window.location.href = this.$window.location.origin  + path;
    };
    redirectTo = (path: string): void => {
        this.$location.path(path);
    };
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/parameter.ts
> +ng.controllers.push(parameterController)
manque la ;

```suggestion
ng.controllers.push(parameterController);
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/parameter.ts
> +import {activeStructureController,parameterMainController, parameterController} from "./controllers/index"
manque la ;


```suggestion
import {activeStructureController,parameterMainController, parameterController} from "./controllers/index";
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/model/parameter/lystore-options.model.ts
> +    exportChoices: ExportChoices
manque la ;


```suggestion
    exportChoices: ExportChoices;
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/model/parameter/lystore-options.model.ts
> +    exportChoices: ExportChoices
manque la ;

```suggestion
    exportChoices: ExportChoices;
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/parameter/parameter.controller.ts
> +            Utils.safeApply(this.$scope)
manque la ;

```suggestion
            Utils.safeApply(this.$scope);
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/parameter-main.controller.ts
> +        this.$window.location.href = this.$window.location.origin  + path
manque la ;

```suggestion
        this.$window.location.href = this.$window.location.origin  + path;
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/parameter-main.controller.ts
> +    redirectToHref = (path: string) => {
typage

```suggestion
    redirectToHref = (path: string): void => {
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/parameter-main.controller.ts
> +    redirectTo = (path: string) => {
typage

```suggestion
    redirectTo = (path: string): void => {
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/model/parameter/bc-options.model.ts
> +        copyAdress.line2 = address.line2
manque la ;


```suggestion
        copyAdress.line1 = address.line1;
        copyAdress.line2 = address.line2;
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/model/parameter/bc-options.model.ts
> +        copyName.line4 = name.line4
manque la ;

```suggestion
        copyName.line1 = name.line1;
        copyName.line2 = name.line2;
        copyName.line3 = name.line3;
        copyName.line4 = name.line4;
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/model/parameter/bc-options.model.ts
> +        copySignature.line2 = signature.line2
manque la ;

```suggestion
        copySignature.line1 = signature.line1;
        copySignature.line2 = signature.line2;
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/services/index.ts
> +export * from "./parameter/parameter-settings"
manque la ;

```suggestion
export * from "./parameter/active-structure";
export * from "./OrderService";
export * from "./parameter/parameter-settings";
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/services/parameter/parameter-settings.ts
> +import {ng} from 'entcore'
manque la ;


```suggestion
import {ng} from 'entcore';
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/services/parameter/parameter-settings.ts
> +    saveBcForm(bcOptions: BcOptions): Promise<void>
manque la ;

```suggestion
    saveBcForm(bcOptions: BcOptions): Promise<void>;
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/active-structure/active-structure.controller.ts
> +import {ActiveStructureService, StructureLystore} from "../../../services"
manque la ;

```suggestion
import {ActiveStructureService, StructureLystore} from "../../../services";
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/active-structure/active-structure.controller.ts
> +    }
manque la ;

```suggestion
    };
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/active-structure/active-structure.controller.ts
> +    }
manque la ;

```suggestion
    };
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/active-structure/active-structure.controller.ts
> +            toasts.info("lystore.deploy.structure.valid")
manque la ;

```suggestion
            toasts.info("lystore.deploy.structure.valid");
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/model/parameter/bc-options.model.ts
> +        let copyBc = new BcOptions();
typage

```suggestion
        let copyBc: BcOptions = new BcOptions();
```

2023-01-31 10:33 UTC, JinDouang commented on src/main/resources/public/ts/controllers/parameter/parameter-main.controller.ts
> +        })
il manque ;
```suggestion
        });
```

2023-02-06 07:52 UTC, merged