feat(Parameter)#MLYSTORE-646: Add changes in BC and CSF from BC form
OPEN-ENT-NG/lystore pull request #90
Opened 2023-02-06 07:19 UTC by Rseuret

2023-02-07 14:57 UTC, Rseuret commented on src/main/java/fr/openent/lystore/service/parameter/impl/DefaultParameterService.java
> +package fr.openent.lystore.service.parameter.impl;
Renomage fichier + déplacement fichier

2023-02-08 09:50 UTC, Rseuret commented on src/main/java/fr/openent/lystore/service/parameter/ActiveStructureService.java
> -package fr.openent.lystore.service;
Renomage fichier + déplacement fichier

2023-02-08 09:51 UTC, Rseuret commented on src/main/java/fr/openent/lystore/service/parameter/impl/DefaultActiveStructureService.java
> +package fr.openent.lystore.service.parameter.impl;
Renomage fichier + déplacement fichier

2023-02-08 09:53 UTC, Rseuret commented on src/main/resources/public/ts/controllers/main.ts
> +        $scope.isSuperAdmin = JSON.parse(window.isSuperAdmin);
obliger car Boolean() renvoyait true tout le temps

2023-02-08 09:54 UTC, Rseuret commented on src/main/resources/public/ts/directives/bc-preview/bc-preview.html
> +<article class="eight twelve-mobile centered">
renomage de fichier avec juste ajout de "vm"

2023-02-08 09:55 UTC, Rseuret commented on src/main/resources/public/ts/directives/parameter-export-choices/parameter-export-choices.html
>          </div>
désactivation des fonctionnalités non implémentées

2023-02-08 10:06 UTC, Rseuret commented on src/main/resources/public/ts/directives/parameter-valid-command/parameter-valid-command.html
> -        <switch-toggle ng-model="vm.hasOperationsAndInstructions" ng-change="vm.onChange()" class="cell">
désactivation des fonctionnalités non implémentées

2023-02-08 10:06 UTC, Rseuret commented on src/main/resources/sql/064-lystore-parameter-bc-options.sql
> +INSERT INTO lystore.parameter_bc_options (name, address, signature, Lock) VALUES('','','','X');
création d'une table ne pouvant contenir qu'un seul élément

2023-02-08 10:06 UTC, Rseuret commented on src/main/java/fr/openent/lystore/security/LystoreManagerAdminAccesOrSuperAdminRight.java
> +public class LystoreManagerAdminAccesOrSuperAdminRight extends SuperAdminFilter implements ResourcesProvider {
doit vérifiant que soit l'utilisateur est superAdmin soit il a des droits de manager ( à minima ) sur Lystore

2023-02-08 10:06 UTC, Rseuret commented on src/main/java/fr/openent/lystore/controllers/parameter/ActiveStructureController.java
> -package fr.openent.lystore.controllers;
renommage de class

2023-02-08 10:20 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExport.java
> +                            log.error("error when getting supplier");
Flag tes erreurs ([Lystore:...])

2023-02-08 10:22 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportAfterValidationStructure.java
> +                        exportHandler.handle(new Either.Left<>("sql failed"));
flag tes erreur

2023-02-08 10:23 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportAfterValidation.java
> +                                    exportHandler.handle(new Either.Left<>("sql failed"));
flag tes erreurs

2023-02-08 10:24 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportBeforeValidationStructure.java
> +                            log.error("error when getting supplier");
flag tes erreurs

2023-02-08 10:24 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportBeforeValidationStructure.java
> +                log.error("An error occurred when retrieving order data");
flag tes erreurs

2023-02-08 10:25 UTC, qpic-cgi commented on src/main/java/fr/openent/lystore/export/validOrders/PDF_OrderHElper.java
> +                log.error("Cannot load image in getBase64File for id : " + imgId);
flag tes erreus

2023-02-08 10:28 UTC, qpic-cgi commented on src/main/resources/public/template/administrator/order/order-send-prepare.html
> +<!--    </article>-->
supprime

2023-02-08 10:30 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/bc-preview/bc-preview.html
> +                        BON DE COMMANDE
on ne peut pas utiliser du i18n pour tout ça ?

2023-02-08 10:36 UTC, qpic-cgi commented on src/main/resources/sql/064-lystore-parameter-bc-options.sql
> +  constraint PK_parameter_bc_options PRIMARY KEY (Lock),
lock ou Lock ?

2023-02-08 10:36 UTC, qpic-cgi commented on src/main/resources/sql/064-lystore-parameter-bc-options.sql
> +INSERT INTO lystore.parameter_bc_options (name, address, signature, Lock) VALUES('','','','X');
Si je comprend bien, lock est en fait un boolean ? quand c'est X c'est true et quand c'est vide c'est false ?

2023-02-08 10:45 UTC, Sofianebernoussi requested changes

2023-02-08 10:45 UTC, Sofianebernoussi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportAfterValidation.java
> +                                    Number supplierId = params.getInteger(LystoreBDD.SUPPLIER_ID);
type int non?

2023-02-08 10:45 UTC, Sofianebernoussi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportAfterValidation.java
> +                                    exportHandler.handle(new Either.Left<>("sql failed"));
message d'erreur plus précis

2023-02-08 10:45 UTC, Sofianebernoussi commented on src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportBeforeValidationStructure.java
> +                            log.error("error when getting supplier");
error pas assez précis

2023-02-08 10:45 UTC, Sofianebernoussi commented on src/main/java/fr/openent/lystore/export/validOrders/PDF_OrderHElper.java
> +                                exportHandler.handle(new Either.Left<>("wrong status when calling bus (pdf) "));
log error pas assez précis

2023-02-08 10:45 UTC, Sofianebernoussi commented on src/main/java/fr/openent/lystore/model/parameter/BCOptionsFormData.java
> +import javax.swing.*;
utile?

2023-02-08 10:45 UTC, Sofianebernoussi commented on src/main/java/fr/openent/lystore/model/parameter/BCOptionsAddress.java
> +public class BCOptionsAddress extends BCOptionsFormData{
pq un model vide?

2023-02-08 10:45 UTC, Sofianebernoussi commented on src/main/java/fr/openent/lystore/model/parameter/BCOptionsSignature.java
> +public class BCOptionsSignature extends BCOptionsFormData{
pq un model vide?

2023-02-08 10:45 UTC, Sofianebernoussi commented on src/main/resources/public/ts/directives/bc-preview/bc-preview.html
> +                        BON DE COMMANDE
i18n un peu partout dans le fichier

2023-02-08 10:45 UTC, Sofianebernoussi commented on src/main/java/fr/openent/lystore/service/parameter/impl/DefaultParameterService.java
> +                    log.error(LystoreUtils.generateErrorMessage(DefaultParameterService.class,
Peut être mieux de stocker les mess d'erreur dans une variable et la reutiliser au lieu de call 2x la meme fonciton pour la meme chose

2023-02-08 10:45 UTC, Sofianebernoussi commented on src/main/java/fr/openent/lystore/service/parameter/impl/DefaultParameterService.java
> +        setBCOptionsName(result, name);
tu peux pas mettre tout ça dans le model?

2023-02-09 13:44 UTC, Rseuret commented on src/main/resources/sql/064-lystore-parameter-bc-options.sql
> +INSERT INTO lystore.parameter_bc_options (name, address, signature, Lock) VALUES('','','','X');
non pas vraiment en gros lock est une constante unique . L'idée c'est que tu force lock a être la PK (donc unique) et le fait que lock doit forcèment être = X (ca aurait marchait avec n'importe quel type de variable). Comme ça tu n'aura qu'une seule entrée dans la table

2023-02-09 13:49 UTC, qpic-cgi commented on src/main/resources/sql/064-lystore-parameter-bc-options.sql
> +INSERT INTO lystore.parameter_bc_options (name, address, signature, Lock) VALUES('','','','X');
donc si je comprend bien, il n'y aura qu'un élément dans ta table SQL ?

2023-02-10 09:36 UTC, Rseuret commented on src/main/resources/sql/064-lystore-parameter-bc-options.sql
> +INSERT INTO lystore.parameter_bc_options (name, address, signature, Lock) VALUES('','','','X');
oui exactement c est une config global de l'appli mais qui est modifiable par plateforme

2023-02-10 10:00 UTC, qpic-cgi commented on src/main/resources/sql/064-lystore-parameter-bc-options.sql
> +INSERT INTO lystore.parameter_bc_options (name, address, signature, Lock) VALUES('','','','X');
Pourquoi ne pas en faire de la config du coup ?

2023-02-10 13:14 UTC, Rseuret commented on src/main/resources/sql/064-lystore-parameter-bc-options.sql
> +INSERT INTO lystore.parameter_bc_options (name, address, signature, Lock) VALUES('','','','X');
car c est les ADMC peuvent modifier depuis un interface de paramètrages

2023-02-10 14:02 UTC, Sofianebernoussi approved these changes

2023-02-13 06:48 UTC, Rseuret commented on src/main/resources/sql/064-lystore-parameter-bc-options.sql
> +INSERT INTO lystore.parameter_bc_options (name, address, signature, Lock) VALUES('','','','X');
https://jira.support-ent.fr/browse/MLYSTOR-646 et https://jira.support-ent.fr/browse/MLYSTOR-626

2023-02-13 06:57 UTC, merged