fix(BC-CSF)#MLYSTOR-646:use of node-pdf to better css
OPEN-ENT-NG/lystore pull request #94
Opened 2023-02-21 14:16 UTC by Rseuret

## Describe your changes
Use node Pdf genreator for better css
## Issue ticket number and link
https://jira.support-ent.fr/browse/MLYSTOR-646
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-02-21 14:17 UTC, Rseuret commented on src/main/resources/public/template/pdf/BC.xhtml
> +
indent

2023-02-22 07:54 UTC, lapeyronnie commented
une petite remarque sur le titre de ta PR : fix(BC-CSF)#MLYSTOR-646:use ... -> les deux point sont plutôt ap fix(BC-CSF)
=> fix(BC-CSF): #MLYSTOR-646 use of node-pdf to better css

2023-02-22 09:07 UTC, JinDouang requested changes

2023-02-22 09:07 UTC, JinDouang commented on deployment/lystore/conf.json.template
> +          "node-pdf-generator" : {
Rajoute le dans conf.j2 pour ODE (copie colle ton instruction)

exemple: https://github.com/OPEN-ENT-NG/cahier-de-textes/blob/dev/deployment/diary/conf.j2#L30

2023-02-22 09:07 UTC, JinDouang commented on src/main/java/fr/openent/lystore/export/validOrders/PDF_OrderHElper.java
> +import static fr.wseduc.webutils.http.Renders.badRequest;
Tu n'as pas l'air de l'utiliser dans tes imports

2023-02-22 09:07 UTC, JinDouang commented on src/main/java/fr/openent/lystore/service/impl/DefaultExportPDFService.java
> +import org.entcore.common.pdf.Pdf;
A confirmer mais en relisant ce fichier je vois pas l'usage de Pdf => supprimer l'import ?

2023-02-22 09:07 UTC, JinDouang commented on src/main/java/fr/openent/lystore/service/impl/DefaultExportPDFService.java
> +                            });
indentation (si possible)

```
 .onFailure(error -> {
                                badRequest(request, error.getMessage());
                                LOGGER.error(LystoreUtils.generateErrorMessage(DefaultExportPDFService.class,
                                        "generatePDF",error.getMessage() ,"error when generatePdfFromTemplate"));
                            });
```

2023-02-22 09:13 UTC, lapeyronnie commented on src/main/resources/public/template/pdf/BC_CSF.xhtml
> +                        A <input type="text" value="..............."/>, le <input type="text"/> <br/>
on pourrait variabiliser la value (".......") et ("../..../..."), non ?

2023-02-22 09:15 UTC, lapeyronnie commented on src/main/resources/public/template/pdf/BC_Struct.xhtml
>                  (Cachet - Signature)
même remarque qu'au dessus

2023-02-22 09:20 UTC, Rseuret commented on src/main/resources/public/template/pdf/BC_CSF.xhtml
> +                        A <input type="text" value="..............."/>, le <input type="text"/> <br/>
indentation

2023-02-22 09:24 UTC, Rseuret commented on src/main/resources/public/template/pdf/BC_CSF.xhtml
> +                        A <input type="text" value="..............."/>, le <input type="text"/> <br/>
l'idéal en soit serait d'avoir un moyen d'avoir les input modifiable en pdf avec le node-pdf-generator pour enlever le placeholder

2023-02-22 10:40 UTC, JinDouang approved these changes

2023-02-22 13:36 UTC, merged